name: On Upstream Push Main - Merge Main

on:
  repository_dispatch:
    types: [sync]

concurrency: merge-main

jobs:
  sync:
    name: Merge Upstream Main to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_SYNC }}
          fetch-depth: 0

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Merge Upstream Main to Main
        run: |
          git fetch https://github.com/ansible/ansible-ui.git main
          git merge --no-ff FETCH_HEAD -m "Merge from upstream"
          git push origin main
