name: On Push Main - Push Release Tag

on:
  push:
    branches:
      - main

concurrency: tag

jobs:
  tag:
    name: Tag Release
    if: github.repository == 'ansible/aap-ui'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_SYNC }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: NPM Version - ${{ inputs.version || 'patch' }}
        run: |
          VERSION=`npm version ${{ inputs.version || 'patch' }} --no-git-tag-version`
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Git Commit Version and Push
        run: |
          git add --all
          git commit -m "${{ env.VERSION }} [skip ci]"
          git push origin --all --no-verify

      - name: Git Tag Version and Push
        run: |
          git commit --allow-empty -m ${{ env.VERSION }}
          git tag -m ${{ env.VERSION }} ${{ env.VERSION }}

      - name: PreCache
        run: npm version 0.0.0 --no-git-tag-version

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Git Tag Push
        run: |
          git push origin --tags --no-verify
