name: EDA Update E2E Server

on:
  workflow_dispatch:
    inputs:
      EDA_SERVER:
        type: string
        description: 'EDA Server'
      UPDATE_SERVER:
        type: boolean
        required: true
        default: false
        description: 'Update server on success'
  schedule:
    - cron: '0 8 * * *'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      EDA_SERVER: ${{ steps.step1.outputs.EDA_SERVER }}
      UPDATE_SERVER: ${{ steps.step1.outputs.UPDATE_SERVER }}
    steps:
      - id: step1
        run: |
          CURRENTDATE=$(date +'%Y%m%d')
          if([ "${{ github.event_name }}" == "workflow_dispatch" ]); then
          echo "EDA_SERVER=${{ github.event.inputs.EDA_SERVER || 'https://eda.ci-ui-${CURRENTDATE}.gcp.testing.ansible.com' }}" >> "$GITHUB_OUTPUT"
          echo "UPDATE_SERVER=${{ github.event.inputs.UPDATE_SERVER }}" >> "$GITHUB_OUTPUT"
          else 
            echo "EDA_SERVER=https://eda.ci-ui-${CURRENTDATE}.gcp.testing.ansible.com" >> "$GITHUB_OUTPUT"
            echo "UPDATE_SERVER=true" >> "$GITHUB_OUTPUT"
          fi

  eda-login:
    name: EDA Login
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - id: login
        env:
          EDA_USERNAME: e2e
        run: |
          if curl -k -f "${{ needs.setup.outputs.EDA_SERVER }}/api/eda/v1/users/" \
              --user "$EDA_USERNAME:${{ secrets.EDA_PASSWORD }}" \
              -o /dev/null; then
              echo "UPDATE_SERVER=true" >> "$GITHUB_OUTPUT"
          else
              echo "UPDATE_SERVER=false" >> "$GITHUB_OUTPUT"
              exit 1
          fi

  eda-update-server:
    name: EDA Update Server
    if: ${{ needs.setup.outputs.UPDATE_SERVER == 'true' }}
    needs:
      - eda-login
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Update Server Variable
        run: |
          curl -f -L -X PATCH -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/variables/EDA_SERVER" \
          -d '{"name":"EDA_SERVER","value":"${{ needs.setup.outputs.EDA_SERVER }}"}'
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments":
                [
                  {
                    "color": "#00DD00",
                    "blocks":
                      [
                        {
                          "type": "section",
                          "text":
                            {
                              "type": "mrkdwn",
                              "text": "*EDA E2E Server Updated*\n${{ github.repository }} - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Success> - <${{ needs.setup.outputs.EDA_SERVER }}|Server>"
                            }
                        }
                      ]
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  slack-failure-notification:
    name: Slack Failure Notification
    if: failure()
    needs:
      - eda-update-server
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments":
                [
                  {
                    "color": "#FF0000",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "*EDA E2E Server Update Failed*\n${{ github.repository }} - *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Failure>* - <${{ needs.setup.outputs.EDA_SERVER }}|Server> - <!here>"
                        }
                      }
                    ]
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK