name: NPM Upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2 * * *'

jobs:
  npm-upgrade:
    name: NPM Upgrade
    if: (github.event_name == 'schedule' && github.repository == 'ansible/ansible-ui') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    concurrency: upgrade
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm run upgrade
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Upgraded package dependencies
