name: Sync Downstream

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: main

jobs:
  merge-to-downstream:
    name: Merge Main to Downstream
    runs-on: ubuntu-latest
    # timeout-minutes: 10

    steps:
      - name: Downstream Merge
        if: github.repository == 'ansible/ansible-ui'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GH_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ansible/aap-ui/dispatches \
          -d '{"event_type":"sync"}'
